<?php if ($maTrang === 'staff-dashboard'): ?>
<div class="librarian-metrics">
  <article><span class="metric-icon navy">▣</span><div><b>18</b><small>Phiếu mượn hôm nay</small></div><em>+4 so với hôm qua</em></article>
  <article><span class="metric-icon coral">↵</span><div><b>12</b><small>Sách trả hôm nay</small></div><em>Đang chờ xử lý: 03</em></article>
  <article><span class="metric-icon amber">!</span><div><b>09</b><small>Tài liệu quá hạn</small></div><em>Cần gửi nhắc nhở</em></article>
  <article><span class="metric-icon mint">₫</span><div><b>245.000đ</b><small>Phí phạt chưa thu</small></div><em>05 độc giả</em></article>
</div>
<div class="librarian-dashboard-grid">
  <section class="panel"><div class="section-head"><div><p class="eyebrow">XỬ LÝ NHANH</p><h2>Quầy lưu thông</h2></div></div><div class="quick-actions"><button class="librarian-action" data-message="Mở trang lập phiếu mượn."><i>+</i><b>Lập phiếu mượn</b><span>Nhập mã độc giả và chọn tài liệu</span></button><button class="librarian-action" data-message="Mở trang tiếp nhận trả sách."><i>↵</i><b>Nhận trả sách</b><span>Kiểm tra tình trạng sách</span></button><button class="librarian-action" data-message="Mở danh sách độc giả quá hạn."><i>!</i><b>Xử lý quá hạn</b><span>09 tài liệu cần nhắc</span></button></div></section>
  <section class="panel"><div class="section-head"><div><p class="eyebrow">LỊCH TRẢ SÁCH</p><h2>Đến hạn hôm nay</h2></div><button class="text-btn librarian-action" data-message="Đã mở danh sách đến hạn hôm nay.">Xem tất cả →</button></div><div class="due-item"><span class="due-date">18<small>THG 09</small></span><div><b>Cơ Sở Dữ Liệu</b><small>Nguyễn Minh Anh · MSSV 22110432</small></div><mark class="yellow">Hôm nay</mark></div><div class="due-item"><span class="due-date">18<small>THG 09</small></span><div><b>Nguyên Lý Kế Toán</b><small>Lê Thị Hương · MSSV 22110820</small></div><mark class="yellow">Hôm nay</mark></div></section>
</div>
<?php elseif ($maTrang === 'borrow-admin'): ?>
<div class="circulation-layout">
  <section class="panel circulation-form"><p class="eyebrow">BƯỚC 1</p><h2>Xác thực độc giả</h2><div class="o-nhap-lieu"><span>⌁</span><input placeholder="Nhập MSSV, MSGV hoặc mã độc giả"><button class="librarian-action" data-message="Đã tìm thấy hồ sơ độc giả.">Tra cứu</button></div><div class="reader-preview"><div class="avatar xl">MA</div><div><b>Nguyễn Minh Anh</b><span>22110432 · Khoa Công nghệ thông tin</span><p><mark class="green-mark">Thẻ hoạt động</mark> Đang mượn 01 / 03 sách</p></div><button class="text-btn librarian-action" data-message="Đã mở hồ sơ Nguyễn Minh Anh.">Hồ sơ →</button></div><p class="eyebrow">BƯỚC 2</p><h2>Thêm tài liệu mượn</h2><p class="form-hint">Tìm theo tên, mã tài liệu hoặc tác giả; có thể chọn nhiều tài liệu cho một phiếu mượn.</p><button class="outline mo-chon-tai-lieu" data-loai="muon">⌕ Tìm và chọn tài liệu</button></section>
  <section class="panel loan-ticket"><div class="section-head"><div><p class="eyebrow">PHIẾU MƯỢN TẠM</p><h2>PM-20260918-019</h2></div><mark class="green-mark">Hợp lệ</mark></div><div class="ticket-book"><i class="blue">◫</i><div><b>Cơ Sở Dữ Liệu</b><span>BC-CNTT-101-08 · Hạn trả 02/10/2026</span></div><button>×</button></div><div class="ticket-summary"><span>Số lượng<b>01 / 03</b></span><span>Thời hạn<b>14 ngày</b></span><span>Phí tạm tính<b>0đ</b></span></div><button class="primary full librarian-action" data-message="Đã lập phiếu mượn PM-20260918-019.">Xác nhận cho mượn <span>→</span></button></section>
</div>
<section class="panel pending-panel">
  <div class="section-head"><div><p class="eyebrow">YÊU CẦU TỪ CỔNG ĐỘC GIẢ</p><h2>Đăng ký mượn đang chờ duyệt <span class="pending-count">03</span></h2></div><button class="text-btn librarian-action" data-message="Đã mở toàn bộ yêu cầu chờ duyệt.">Xem tất cả →</button></div>
  <div class="table-panel pending-table"><table><thead><tr><th>ĐỘC GIẢ</th><th>TÀI LIỆU ĐĂNG KÝ</th><th>THỜI GIAN GỬI</th><th>KIỂM TRA</th><th>THAO TÁC</th></tr></thead><tbody>
    <tr data-yeu-cau-cho><td><b>Lê Thị Hương</b><span>22110820 · Khoa Kinh tế</span></td><td><b>Nguyên Lý Kế Toán</b><span>KT-021 · Còn 06 bản</span></td><td>18/09/2026 · 08:42</td><td><mark class="green-mark">Thẻ hợp lệ</mark></td><td><button class="duyet-yeu-cau" data-message="Đã duyệt yêu cầu mượn của Lê Thị Hương.">Duyệt</button><button class="tu-choi-yeu-cau" data-message="Đã từ chối yêu cầu mượn của Lê Thị Hương.">Từ chối</button></td></tr>
    <tr data-yeu-cau-cho><td><b>Phạm Quốc Bảo</b><span>22110615 · Khoa Luật</span></td><td><b>Giáo Trình Luật Dân Sự Việt Nam</b><span>LUAT-032 · Còn 04 bản</span></td><td>18/09/2026 · 09:10</td><td><mark class="green-mark">Thẻ hợp lệ</mark></td><td><button class="duyet-yeu-cau" data-message="Đã duyệt yêu cầu mượn của Phạm Quốc Bảo.">Duyệt</button><button class="tu-choi-yeu-cau" data-message="Đã từ chối yêu cầu mượn của Phạm Quốc Bảo.">Từ chối</button></td></tr>
    <tr data-yeu-cau-cho><td><b>Trần Gia Huy</b><span>22110218 · Khoa Luật</span></td><td><b>Pháp Luật Đại Cương</b><span>LUAT-008 · Hiện hết bản</span></td><td>18/09/2026 · 09:26</td><td><mark class="red-mark">Thẻ tạm khóa</mark></td><td><button class="duyet-yeu-cau vo-hieu" disabled>Không thể duyệt</button><button class="tu-choi-yeu-cau" data-message="Đã từ chối yêu cầu do thẻ độc giả tạm khóa.">Từ chối</button></td></tr>
  </tbody></table></div>
</section>
<?php elseif ($maTrang === 'return-admin'): ?>
<div class="circulation-layout return-layout">
  <section class="panel circulation-form"><p class="eyebrow">CHỌN TÀI LIỆU</p><h2>Tiếp nhận trả sách</h2><p class="form-hint">Tìm và chọn một hoặc nhiều tài liệu đang được độc giả mượn để tiếp nhận trả cùng lúc.</p><button class="outline mo-chon-tai-lieu" data-loai="tra">⌕ Tìm tài liệu cần trả</button><div class="return-book"><i class="green">↗</i><div><b>Kinh Tế Vi Mô</b><span>KT-044 · N. Gregory Mankiw</span><p>Độc giả: Nguyễn Minh Anh · Mượn ngày 04/09/2026</p></div></div><label class="condition-label">Tình trạng khi nhận<select><option>Nguyên vẹn</option><option>Hư hỏng nhẹ</option><option>Hư hỏng nặng</option></select></label></section>
  <section class="panel return-result"><p class="eyebrow">KẾT QUẢ KIỂM TRA</p><h2>Thông tin hoàn trả</h2><div class="return-line"><span>Hạn trả</span><b>18/09/2026</b></div><div class="return-line"><span>Ngày trả</span><b>18/09/2026</b></div><div class="return-line"><span>Quá hạn</span><b class="ok-text">Không</b></div><div class="return-line total"><span>Phí cần thu</span><b>0đ</b></div><button class="primary full librarian-action" data-message="Đã xác nhận trả sách. Bản sách chuyển về trạng thái sẵn sàng.">Xác nhận trả sách <span>→</span></button></section>
</div>
<?php elseif ($maTrang === 'reader-admin'): ?>
<section class="panel reader-management"><div class="inventory-toolbar"><div class="inventory-search"><span>⌕</span><input class="librarian-search" placeholder="Tìm MSSV, MSGV, họ tên hoặc email..."></div><select class="inventory-filter"><option>Tất cả trạng thái thẻ</option><option>Hoạt động</option><option>Đã khóa</option><option>Hết hạn</option></select><button class="primary librarian-action" data-message="Mở biểu mẫu tạo hồ sơ độc giả.">+ Thêm độc giả</button></div><div class="table-panel inventory-table"><table><thead><tr><th>ĐỘC GIẢ</th><th>MSSV / MSGV</th><th>KHOA</th><th>ĐANG MƯỢN</th><th>PHÍ PHẠT</th><th>TRẠNG THÁI</th><th></th></tr></thead><tbody><tr><td><b>Nguyễn Minh Anh</b><span>minhanh@university.edu.vn</span></td><td>22110432</td><td>Công nghệ thông tin</td><td>01 / 03</td><td>0đ</td><td><mark class="green-mark">Hoạt động</mark></td><td><button class="table-action librarian-action" data-message="Đã mở hồ sơ Nguyễn Minh Anh.">Chi tiết</button></td></tr><tr><td><b>Lê Thị Hương</b><span>huonglt@university.edu.vn</span></td><td>22110820</td><td>Kinh tế</td><td>03 / 03</td><td>15.000đ</td><td><mark class="yellow">Cảnh báo</mark></td><td><button class="table-action librarian-action" data-message="Đã mở hồ sơ Lê Thị Hương.">Chi tiết</button></td></tr><tr><td><b>Trần Gia Huy</b><span>huytg@university.edu.vn</span></td><td>22110218</td><td>Luật</td><td>00 / 03</td><td>60.000đ</td><td><mark class="red-mark">Tạm khóa</mark></td><td><button class="table-action librarian-action" data-message="Đã mở hồ sơ Trần Gia Huy.">Chi tiết</button></td></tr></tbody></table></div></section>
<?php elseif ($maTrang === 'fines'): ?>
<div class="fine-stats"><article><span>TỔNG CHƯA THU</span><b>245.000đ</b><small>09 phiếu phạt đang mở</small></article><article><span>ĐÃ THU HÔM NAY</span><b>75.000đ</b><small>04 giao dịch</small></article><article><span>QUÁ HẠN TRÊN 30 NGÀY</span><b>02</b><small>Cần xử lý ưu tiên</small></article></div><section class="panel fine-panel"><div class="inventory-toolbar"><div class="inventory-search"><span>⌕</span><input class="librarian-search" placeholder="Tìm độc giả, mã phiếu phạt..."></div><select class="inventory-filter"><option>Chưa thanh toán</option><option>Đã thanh toán</option><option>Miễn giảm</option></select><button class="outline librarian-action" data-message="Đã xuất danh sách phạt dạng báo cáo.">⇩ Xuất báo cáo</button></div><div class="table-panel inventory-table"><table><thead><tr><th>PHIẾU PHẠT</th><th>ĐỘC GIẢ</th><th>LÝ DO</th><th>SỐ TIỀN</th><th>HẠN THANH TOÁN</th><th>TRẠNG THÁI</th><th></th></tr></thead><tbody><tr><td><b>VP-2026-031</b><span>Lập 16/09/2026</span></td><td>Trần Gia Huy<span>22110218 · Luật</span></td><td>Quá hạn 12 ngày</td><td><b>60.000đ</b></td><td>23/09/2026</td><td><mark class="red-mark">Chưa thu</mark></td><td><button class="table-action librarian-action" data-message="Mở phiếu thu VP-2026-031.">Thu tiền</button></td></tr><tr><td><b>VP-2026-028</b><span>Lập 14/09/2026</span></td><td>Lê Thị Hương<span>22110820 · Kinh tế</span></td><td>Quá hạn 03 ngày</td><td><b>15.000đ</b></td><td>21/09/2026</td><td><mark class="yellow">Chưa thu</mark></td><td><button class="table-action librarian-action" data-message="Mở phiếu thu VP-2026-028.">Thu tiền</button></td></tr></tbody></table></div></section>
<?php endif; ?>


